name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install the library
      run: |
        pip install nbdev jupyter
        pip install -e .
    - name: Check if all notebooks are cleaned
      run: |
        which python
        which nbdev_read_nbs
        nbdev_read_nbs
        if [ -n "$(git status -uno -s)" ]; then echo "git status is not clean"; false; fi
        nbdev_clean_nbs
        git status -s # display the status to see which nbs need cleaning up
        [[ -n "$(git status -uno -s)" ]] && echo -e "!!! Detected unstripped out notebooks\nRemember to run nbdev_install_git_hooks" && false
        [[ -n "$(nbdev_diff_nbs)" ]] && echo -e "!!! Detected difference between the notebooks and the library" && false
    - run: nbdev_test_nbs
