name: Python
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
#     - uses: actions/cache@v2
#       with:
#         path: ${{ env.pythonLocation }}
#         key: ${{ runner.os }}-pydeps-${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}
    - name: Install requirements
      run: |
        python --version
        pip install --upgrade --upgrade-strategy eager -r dev-requirements.txt
